matryer/moq

package/moq/moq.go, package/moq/moq_test.go, package/moq/testdata/channels/example.go
This fixes #11, where `<` character was escaped, e.g. in `chan<- struct{}`.
=> Change `html/template` to `text/template`

pkg/moq/moq_test.go
The TestDotImports changed the directory, so every test afterwards was executed from another directory and calls like New("testpackages/emptyinterface", "") failed.
=> [PATCH] Remove side effect caused by chdir from test - fixes #23

pkg/moq/moq_test.go
The test case checked for a whole package path, which should exist in a generated moq file, but that failed for obvious reasons in forks.
I just removed the part, which is different in the forks to pass the test. If you don't think, that this is sufficient, I can change it.
=> [PATCH] Made tests independent from package path

.travis.yml
Golint won't even install currently.
Also change the `go get` command to use `golang.org/x/lint/golint`.
Fixes #75
=> Test on supported versions of Go

pkg/moq/moq.go
Same as #76. Fixes #84
`go/packages` understands how to locate packages in a module-aware manner.
I've started to use go mod and got a lot of errors like this:
```
<project path outside GOPATH>/vendor/github.com/spf13/viper/viper.go:42:7: could not import github.com/pelletier/go-toml (go/build: importGo github.com/pelletier/go-toml: exit status 1
can't load package: package github.com/pelletier/go-toml: cannot find package "." in:
<project path outside GOPATH>/vendor/github.com/spf13/viper/vendor/github.com/pelletier/go-toml
```
=> Go modules support

pkg/moq/moq.go, pkg/moq/moq_modules_test.go, pkg/moq/testpackages/modules/go.mod, pkg/moq/testpackages/modules/simple.go
Previous code couldn't load correct package path outside gopath. `packagePath := stripGopath(filepath.Join(wd, src, packageName))` was returning a full directory name and packageQualifier wasn't able to detect the same package path. Now all the packages are loading with go/packages.  
Also added a couple of tests for go modules.
Fixes #92
=> fix cyclic dependency with go modules

.travis.yml, pkg/moq/moq.go, pkg/moq/moq_test.go
This fixes #103 and also fixes #102
=> Fix moq for go 1.13 and avoid creating empty directory

README.md, main.go, pkg/moq/moq.go, pkg/moq/moq_test.go, pkg/moq/template.go
Implementation based on #57.
~~Additionally, handle the destination pkg having 'mock' in its name.~~ - not necessary, the user can define the alias as per their requirement.
TODO: Update README(need some tips)
Closes #57 
Closes #106 
Closes #67
=> Allow aliasing interface name

pkg/moq/template.go
If the user specifies a different package and the mock name is the same
as the interface name, the type guard comment will be of the following
format:
```
Ensure, that MyInterface does implement MyInterface.
```
So use the `$sourcePackagePrefix` in the comment.
=> Improve comment on type guard in template

.travis.yml
If a PR is created using a branch pushed to origin, this triggers travis
CI twice(see #113), once for the PR and another for the branch. So run Travis CI for
only the `master` branch and when PRs are created using origin branches.
If CI needs to be run on any specific branch other than `master`, it would
need to be whitelisted.
=> Run travis CI only on master branch and PRs

.gitignore, pkg/moq/moq.go
From the docs for `packages.{LoadFiles, LoadSyntax}` -
https://godoc.org/golang.org/x/tools/go/packages#pkg-constants
// Deprecated: LoadFiles exists for historical compatibility
// and should not be used. Please directly specify the needed
// fields using the Need values.
// ...
// Deprecated: LoadSyntax exists for historical compatibility
// and should not be used. Please directly specify the needed
// fields using the Need values.
=> Avoid deprecated LoadMode packages.{LoadFiles, LoadSyntax}

pkg/moq/moq.go, pkg/moq/moq_test.go, pkg/moq/testpackages/vendoring/vendor/github.com/matryer/somerepo/code.go
When the interface that we are trying to moq is present inside the vendor
directory and the output package name is different, the import needs to be
stripped of the vendor path.
Closes #18 (see https://github.com/matryer/moq/issues/18#issuecomment-463004812)
=> Handle target interface inside vendor with other pkg name

main.go, pkg/moq/moq_modules_test.go, pkg/moq/moq_test.go
[Gosec](https://github.com/securego/gosec) found some vulnerabilities:
* Expect directory permissions to be 0750 or less
* Expect WriteFile permissions to be 0600 or less
based on https://cwe.mitre.org/data/definitions/276.html
=> fix gosec vulnerabilities: file and directory permissions

internal/registry/method_scope.go, internal/registry/var.go, pkg/moq/testpackages/paramconflict/iface.go, pkg/moq/testpackages/paramconflict/iface_moq.golden.go
When the type and the package name is the same for an anonymous
parameter (ex: time.Time), and there are more than 1 such parameters,
the generated name for both was the same. And the generated code would
not be valid.
Fix the bug by ensuring the parameter name does not conflict with
package imports first before checking against other parameter names.
Closes #144 
cc: @breml
=> Fix var name generation to avoid conflict

README.md
Fixed how to install of README for go1.16+.
Because go1.16 and later, `go install` is recommended way for get & build cli tool.
Check this link for details.
https://tip.golang.org/doc/go1.16#go-command
>go install, with or without a version suffix (as described above), is now the recommended way to build and install packages in module mode. go get should be used with the -d flag to adjust the current module's dependencies without building packages, and use of go get to build and install packages is deprecated. In a future release, the -d flag will always be enabled.
=> fix how to install of README for go1.16+

.goreleaser.yml, releasing.md
A special format that contains both arm64 and amd64 executables in a single file.
=> Universal binaries for macOS

.github/workflows/release.yml, .goreleaser.yml
Requested in https://github.com/matryer/moq/pull/171#issuecomment-1084293950
=> Add goreleaser github action

.github/workflows/release.yml, .github/workflows/test.yml, go.mod, go.sum, internal/template/template.go, pkg/moq/testpackages/anonimport/iface_moq.golden.go, pkg/moq/testpackages/blankid/swallower.golden.go, pkg/moq/testpackages/channels/queuer_moq.golden.go, pkg/moq/testpackages/generics/generics_moq.golden.go, pkg/moq/testpackages/genparamname/iface_moq.golden.go, pkg/moq/testpackages/gogenvendoring/user/user_moq_test.go, pkg/moq/testpackages/importalias/middleman_moq.golden.go, pkg/moq/testpackages/imports/two/gofmt.golden.go, pkg/moq/testpackages/imports/two/goimports.golden.go, pkg/moq/testpackages/imports/two/noop.golden.go, pkg/moq/testpackages/paramconflict/iface_moq.golden.go, pkg/moq/testpackages/shadow/mock/thing_moq.golden.go, pkg/moq/testpackages/shadow/shadower_moq.golden.go, pkg/moq/testpackages/shadowtypes/shadowtypes_moq.golden.go, pkg/moq/testpackages/syncimport/syncer_moq.golden.go, pkg/moq/testpackages/variadic/echoer.golden.go
- Only test on 1.19 for Windows and Mac.
- Bump versions for checkout and setup-go actions. Use cache flag in 
setup-go instead of separate cache step.
=> Test on Go 1.{18, 19}

internal/registry/registry.go, internal/registry/registry_test.go
This merge request is a performance improvement to address #178. The merge request contains two commits, in which the first commit adds a benchmark test. This allows the benchmark test to be executed before and after the changes in the second commit for comparison. Further optimization may be required to close #178, but I hope that this merge request is a step in the right direction.
The following are the benchmark results on my dev machine:
Before:
```
$ go test -bench=. ./internal/registry -count 3
goos: linux
goarch: amd64
pkg: github.com/matryer/moq/internal/registry
cpu: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
BenchmarkNew-8                 3         335638233 ns/op
BenchmarkNew-8                 4         328678100 ns/op
BenchmarkNew-8                 4         322492350 ns/op
PASS …
```
=> Do not load unnecessary package information

go.mod, go.sum
After I update to go `1.22.0`, running moq is panic with `runtime error: invalid memory address or nil pointer dereference`.
Updating `golang.org/x/tools` fix the issue.
My command:
```sh
moq -out ads_mock_generated.go . AdsService
```
The panic:
```txt
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102eaa670]
goroutine 2295 [running]:
go/types.(*Checker).handleBailout(0x14000264e00, 0x1400003dbe8)
/usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x1030112c0?, 0x103240b80?})
/usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x103060238, 0x103244500}) …
```
=> build: bump golang.org/x/tools v0.17.0

.github/workflows/release.yml, .github/workflows/test.yml
Test for supported Go versions and utilizing the new “stable” and “oldstable” version aliases to avoid having to update this for each successive Go version.
=> .github/test.yml: Run tests on latest supported Go versions

internal/template/template_data.go, pkg/moq/testpackages/anonimport/iface.go, pkg/moq/testpackages/anonimport/second_file.go, pkg/moq/testpackages/blankid/swallower.go, pkg/moq/testpackages/genericreturn/genericreturn.go, pkg/moq/testpackages/genericreturn/otherpackage/otherpackage.go, pkg/moq/testpackages/generics/generics.go, pkg/moq/testpackages/genparamname/iface.go, pkg/moq/testpackages/importalias/middleman.go, pkg/moq/testpackages/importalias/source/client/src_client.go, pkg/moq/testpackages/importalias/target/client/tgt_client.go, pkg/moq/testpackages/paramconflict/iface.go, pkg/moq/testpackages/shadow/http/thing.go, pkg/moq/testpackages/shadowtypes/shadowtypes.go, pkg/moq/testpackages/shadowtypes/types/types.go, pkg/moq/testpackages/syncimport/sync/thing.go, pkg/moq/testpackages/syncimport/syncer.go, pkg/moq/testpackages/transientimport/base/type.go, pkg/moq/testpackages/transientimport/four/app/v1/four.go, pkg/moq/testpackages/transientimport/one/v1/one.go, pkg/moq/testpackages/transientimport/onev1/zero.go, pkg/moq/testpackages/transientimport/three/v1/three.go, pkg/moq/testpackages/transientimport/transient.go, pkg/moq/testpackages/transientimport/two/app/v1/two.go, pkg/moq/testpackages/variadic/echoer.go, pkg/moq/testpackages/vendor/github.com/sudo-suhas/moq-test-pkgs/somerepo/code.go, pkg/moq/testpackages/vendoring/vendor/github.com/sudo-suhas/moq-test-pkgs/somerepo/code.go
These popped up as linters checked on another PR, so I figure I would fix them.
=> Fix GitHub check annotations

internal/template/template.go, pkg/moq/moq_test.go, pkg/moq/testpackages/withresets/withresets.go, pkg/moq/testpackages/withresets/withresets_moq.golden.go
Resolves https://github.com/matryer/moq/issues/228
=> Add Generics support to -with-resets

go.mod, go.sum
Fix `package "context" without types was imported from "xxx/pkg"`
See https://github.com/vektra/mockery/issues/535
=> build: bump golang.org/x/tools v0.30.0

.github/workflows/release.yml, go.mod
With go 1.24, `go install github.com/matryer/moq@latest` works but binaries from https://github.com/matryer/moq/releases/tag/v0.5.2 doesn't work.
> package requires newer Go version go1.24 (application built with go1.23)
=> build: Update go to 1.24

go.mod
Support Go `1.25`
Closes https://github.com/matryer/moq/issues/237
=> build with go 1.25
